### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [bio-tools/biotools-github-editor#1]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/bio-tools/biotools-github-editor/blob/master/package.json#L20

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by ValentinMarcon** [comment]
Hello,
You're  right, I was using it for development tests and forgot to remove it.
